### ISSUE TITLE
How can i set enable/disable editing dynamic？

### ISSUE THREAD

**Issue by satoshinosekai** [unwild/SimpleTableCellEditor#1]
Hello, i need to dynamic set it can editing or not, did i do that?

**Comment by unwild** [comment]
Hello,

You can toggle your editing class, or override the validation method to use a global flag.

edit: I think it wouldn't be bad to add a toggle function. I can do this if it fits your needs. let me know.

Regards

**Comment by unwild** [comment]
Toggle option has been added. Try it out there : https://codepen.io/HugRob/pen/WNbKNZP
