### ISSUE TITLE
Trim leading and trailing spaces on enter edit mode

### ISSUE THREAD

**Issue by Terbium-135** [unwild/SimpleTableCellEditor#3]
I tried to accomplish this using the given hooks but no success.

Given this html layout you will get spaces in front of and after the `TEXT` shown in the input field on editing
```
            <td class="align-middle editMe">
                          TEXT
            </td>
```

That aside I like the pure and clean look of this table editor.
Keep going!

**Comment by unwild** [comment]
Hello,

You can override the internals to get desired behaviour : 

Here I pasted the default extractValue function and added a trim() :

`
editor.SetEditableClass("editable", {internals:{extractValue: (elem) => { return $.trim($(elem).text()); }}});
`
