### ISSUE TITLE
Make width of the editor input field not wider than the table cell

### ISSUE THREAD

**Issue by Terbium-135** [unwild/SimpleTableCellEditor#4]
At least as an configurable option?
If the table column is small he table contents get moved around which is (in my opinion) visual disturbing

**Comment by unwild** [comment]
Hello hg-runs. The library does not take care of the style, it is javascript only. The behavior here is caused by the absence of defined width on the columns.

I'm currently busy but i can give you in the next days some examples of workarounds if you want.

**Comment by unwild** [comment]
If you don't want the cell to change width when editing you can : 

- Add fixed width to your th or td
- Change the default editor function or add a css class to it (see cellParams.internals.renderEditor)

This library do not take care of any style, it is JS only.
