### ISSUE TITLE
All tables are activated, independant of ID

### ISSUE THREAD

**Issue by sousys** [unwild/SimpleTableCellEditor#5]
i tried to make tables with an id in an element editable and tables without id not editable. 
But all tables in the element are editable after this 

`function tableEdit() {

	let doc = $(document).find('#doc_container').find('table')
	for (let table of doc) {
		let id = table.getAttribute('id')
		if (id) {
			new SimpleTableCellEditor(id).SetEditable("td", {
				behaviour: {
					outsideTableClickCauseCancellation: true
				}
			})
		}
	}
}
`

**Comment by unwild** [comment]
Yeah, I tried it and you're right. The thing is SetEditable() takes a Jquery element or a class.
So giving it a selector like 'td' juste broke the library.

I'll look into it later this weekend to see if I can give you a better approach.

**Comment by sousys** [comment]
class-based would be great, but on `<table>` instead of td. with the option to give children class "uneditable" or something to lock them from edit.

**Comment by sousys** [comment]
I like that i can enable all tables easily so i modified SetEditable to facilitate exclusion of class on both table and td. 

`
    SetEditable(elem, _cellParams, excludeClass="uneditable") {
        var _instance = this;

        if (!_instance._isValidElem(elem))
            return;

        var cellParams = _instance._GetExtendedCellParams(_cellParams);


        //If click on td (not already in edit ones)
        $(elem).on('click', function (evt) {

            if(!_instance.active) {
                return
            }

            if ( $(this).hasClass(_instance.params.inEditClass) ) {
                return
            }

            if ( $(this).hasClass(excludeClass) ) {
                return
            }

            if ( $(this).closest('table').hasClass(excludeClass) ) {
                return
            }

            _instance._EditCell(this, cellParams);

        });


        $(elem).on('keydown', function (event) {

            if(!_instance.active)
                return;

            if (!$(this).hasClass(_instance.params.inEditClass))
                return;

            _instance._HandleKeyPressed(event, this, cellParams);

        });

    }`

And i can simply call this once:
`	
new SimpleTableCellEditor().SetEditable("td", {
		behaviour: {
			outsideTableClickCauseCancellation: true
		}
	})
`

I also modified  _HandleKeyPressed to enable navigation. when _instance.tableID == 'table'

**Comment by sousys** [comment]
As a sidenote, i found this lib via https://www.jqueryscript.net/table/inplace-editing-table-simpletablecelleditor.html where the instructions specifically mention setEditable("td") as a way of enabling edition.

**Comment by unwild** [comment]
Hello sousys,

Thanks a lot for your PR, I've been real sick this weekend, i'll check it this evening (France time).

I really like your excludeClass idea.

P.S : I know, this tutorial is wrong and many people emailed me because they can't get it to work.
