### ISSUE TITLE
"onEditEnter" event for a cell is fired before the "edited" event for the previous cell

### ISSUE THREAD

**Issue by philtao-dev** [unwild/SimpleTableCellEditor#7]
Hi, just a glitch for which I propose a solution...
I have a table where I set the "internals" of a cell depending on the value in another cell.
for example cell "type" can be A or B.  cell "val" is a number from 1 to 20 if "type" is A, or number from 1 to 6 if "type" is B

for cell "type" I save the entered value in a variable using the "cell:edited" event: 
`  $('#bit_tbl').on("cell:edited", function (evt) {
    if (evt.element.classList.contains("type")) {
      t = evt.newValue;
    }
  });
`
for cell "val" the $(elem).html is a variable "val_internals"
`bitEditor.SetEditableClass("val", {
    internals: {
      renderEditor: (elem, oldVal) => {
          $(elem).html(val_internals);
    			let input = $(elem).find('input');
    			input.focus();
    			input.val(oldVal);      }
    }
  });`

the `val_internals` variable is set onEditEnter:
`$('#bit_tbl').on("cell:onEditEnter", function (evt) {
    if (evt.element.classList.contains("val")) {
      if (t.includes('trigger')) {
        val_internals = "<input type='number' min='1' max='20'>";
      } else if (t.includes('output')) {
        val_internals = "<input type='number' min='1' max='6'>";
      } else {
        val_internals = "<input type='number' min='0' max='1'>";
      }
    }`

It works great most of the time, except when after editing cell "type" I click on cell "val".  The "val_internals" is not properly set.  the "onEditEnter" event for the second cell is fired before the "edited" event on the previous cell...  so the variable "t" is not yet set.

To fix it I moved the "We free up hypothetical previous cell" code before the "Triggering before entering edition mode event" in the function "_EditCell(elem, cellParams)":

`_EditCell(elem, cellParams) {
        //We free up hypothetical previous cell
        this._FreeCurrentCell(this.EditionEndOrigin.AnotherCell);
        //Triggering before entering edition mode event
        var onEditEnterEvent = this._FireOnEditEnterEvent(elem);
        .......`
Seems to work fine now.  Just hope I did not break anything else.
Thank you for sharing your code.
Philippe

**Comment by unwild** [comment]
Hi Phillippe,

Sorry for the ~2+ years. Thanks for the debugging, I will take some time to look into this issue.

Glad you've been able to fix it on your side.

Hugo
