### ISSUE TITLE
validators: Currency

### ISSUE THREAD

**Issue by Tundus** [unwild/SimpleTableCellEditor#8]
Hi, 

I just wanted to add a validator which checks if the cell value is currency but could not find a way! In your examples it is either null of $is.Numeric! Could you please give me an idea how to add a currency validator?

Many thanks,

Tundus

**Comment by unwild** [comment]
Hi Tundus,

You will have to call your own input validation function from the validation function. I can help you find a currency validation package if you give more details. Is the value going to be numeric + currency symbol or only a currency symbol or name ?

If you need to keep it simple, you can find a currency symbol + name list online and check if the user input is in that list.

**Comment by Tundus** [comment]
I might have misled you for which I am sorry because I have just checked back what I really want to achieve and realized that the problem with $isNumeric was that -23 is not recognized as a numeric value. So validation didn't work for me on negative numbers or I used the wrong negative symbol!

**Comment by unwild** [comment]
No problem ! To be honest this code is just an exemple of the validation usage, I don't know how well jquery is handling the IsNumeric function.

Hoping you find what you need.
